### ISSUE TITLE
Can't fetch `sub_district_en` from WarsCaseLocation table

### ISSUE THREAD

**Issue by elvinyhlee** [vote4hk/warsinhk#140]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
I get this error while running `gatsby develop`
![image](https://user-images.githubusercontent.com/39041751/75217637-8a1b1200-57d2-11ea-98e7-fa8bdcc59655.png)
Reason: The field is missing in spreadsheet
![image](https://user-images.githubusercontent.com/39041751/75217513-314b7980-57d2-11ea-9853-c59b765450f9.png)

**Comment by cswbrian** [comment]
Thanks for spotting. Issue fixed.
