### ISSUE TITLE
feat: Global Cases tab

### ISSUE THREAD

**Issue by elvinyhlee** [vote4hk/warsinhk#141]
Me and my friend (Designer) are willing to contribute in this project.

**I'm submitting a ...**
  - [X] feature request

**Reason**
1. Coronavirus is spreading out quickly across world (South Korea, Iran, etc.). It will be helpful if we include summary of global situation.
2. There are similar dashboards out there but most are in English and Simplified chinese, I would like to make a Traditional chinese version.

**Detailed explanation**

* All the data will be sourced from WHO daily report.
https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports/

* Content to be included in the page:
Trend, global ranking, heat map (maybe), open for discussion.

**Sketch**
This is definitely a draft, without any style and concrete content.
If you guys are ok with the idea, my designer friend is going to help in redesigning the page.

![image](https://user-images.githubusercontent.com/39041751/75378274-593ff780-590e-11ea-9833-75d77857d680.png)

**Comment by nandiheath** [comment]
feel free to join our telegram channel: https://t.me/joinchat/BwXunhP9xMWBmopAFrvD8A

**Comment by elvinyhlee** [comment]
@nandiheath The invite link is invalid.

**Comment by cswbrian** [comment]
There's a good website for the global cases
https://thewuhanvirus.com/zh/

I suggest we can take a reference and adding the global data in our landing page, instead of having one more page.

**Comment by nandiheath** [comment]
https://t.me/joinchat/Fkp2iFe2ZZYWb7KZ8c78hg
sorry this is the link 🙏
