### ISSUE TITLE
Global Cases Improvement suggestion

### ISSUE THREAD

**Issue by kalvin807** [vote4hk/warsinhk#162]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
1. As a user, I want to go to the corresponding source/ consulate page for further information.

2. As a user, I also want the information from the airline companies of the special pandemic arrangement, so that I can find travel-related information easily.

What is the expected behaviour?
1. Each chip has a clickable link to the corresponding page.
2. New tab displaying information about airline arrangement

What is the motivation/use case for changing the behaviour?
Small change to chip component with no library change.
A new tab in Global Case tab list

I can work on it if you guys think these are good to have feature. :)

**Comment by cswbrian** [comment]
Thanks for the suggestions!
Our website is expected to support (1), it would include the data source/consulate link, just pending some little code work and data input.
https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vQOnfZtGysW5qVe9FferSvhSODKa9ASH7SeqCGAGJSz8ZV7POm3kzFqfkbVAgryHKdj9WwLKXJai332/pub?gid=0

For (2), in my opinion, I think a user would go to the airline website directly if he/she has already got the ticket, so it may be a little bit lower priority comparing to others 🙏

**Comment by kalvin807** [comment]
The newly merged pr ( #161 ) covered my suggestion. I will close this issue.
