### ISSUE TITLE
Frontpage statistic and cases page mismatch

### ISSUE THREAD

**Issue by yookoala** [vote4hk/warsinhk#179]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
A bug.

* **What is the current behavior?**
The  frontpage stated that there is only **5** new cases on the frontpage summary (as rendered on 23rd March, 2020) while I counted 39 cases confirmed on 23rd March in the [Cases page](https://wars.vote4.hk/cases).

The frontpage summary (captured at 14:53, 24th March, 2020):
![2020-03-24 14-53-53 的螢幕擷圖](https://user-images.githubusercontent.com/91274/77397163-0ad42a80-6de0-11ea-8524-f9ee0dc60996.png)

The cases page (captured at 14:57, 24th March, 2020) shows at least the first 6 cases to be confirmed on 23rd. The page is long, but I counted 39 total cases:
![2020-03-24 14-57-17 的螢幕擷圖](https://user-images.githubusercontent.com/91274/77397170-0d368480-6de0-11ea-87f7-c3f0021e6ec8.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
As demonstrated above.

* **What is the expected behavior?**
The figures should be consistent with the cases list, or there are other display issue that caused the misunderstanding.

* **What is the motivation / use case for changing the behavior?**
To better communicate the epidemic situation.

* **Please tell us about your environment:**
  
  - Version: 2.0.0-beta.X
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by kalvin807** [comment]
It is due to the data is not here yet. If you go to the [CHP website](https://www.coronavirus.gov.hk/chi/index.html) (as of 24 March 17:14), the number of total cases and the number of cases with details are also not in sync. Therefore, there is no fix for it, perhaps a sidenote explaining this may help.

**Comment by yookoala** [comment]
@kalvin807: I believe the case list is rendered from scrapping [this PDF](https://www.chp.gov.hk/files/pdf/local_situation_covid19_tc.pdf) (please correct me). So there is a different data source about the "latest case number" from the case list. So could you (or other developer) please help explaining more about:

1. How the number of total cases is rendered? and
2. How the "last update" date is rendered?

I understand there are problem with the source data. I think there might be way to present the data to prevent confusion. Thanks.

**Comment by kalvin807** [comment]
Both numbers of total cases and last update are fetched from CHP by a bot. 
See implementation [here](https://github.com/nandiheath/warsinhk-cronjobs/tree/master/wars-figures) and data source [here](http://www.chp.gov.hk/files/misc/latest_situation_of_reported_cases_wuhan_chi.csv).

While the data of details of each confirmed case is maintained by volunteers.

**Comment by cswbrian** [comment]
There was a 'View more' button at the after the most 5 (or 10 for desktop) new cases in the front page.
It is accidentally removed after the release of modular feature on Sunday.
@nandiheath

**Comment by cswbrian** [comment]
@yookoala nearly all our data are manually inputted as CHP data is updated at midnight 0200 next day, which is already too late.

The below data is inputted by me directly :0)
How the number of total cases is rendered? and
How the "last update" date is rendered?

**Comment by yookoala** [comment]
I'm checking on the source [本港2019冠狀病毒病的最新情況](https://data.gov.hk/tc-data/dataset/hk-dh-chpsebcddr-novel-infectious-agent/resource/5195d815-8d71-4e4e-8787-950de3366f46) ([this csv that the site is using](http://www.chp.gov.hk/files/misc/latest_situation_of_reported_cases_wuhan_chi.csv)). I found no description on what those columns are meant to be.

I presumed:
```
符合呈報準則個案 = 確診個案 + 排除個案 + 仍然住院接受檢查個案 + 疑似個案
```

which matches most of the days, but not all. On the 21st March row, this equation gives -2. And yesterday, the equation gives -13. What the XXXX?

**Comment by kalvin807** [comment]
Hong Kong Government :)
