### ISSUE TITLE
Untranslated `cases.status_pending_admission` in cases page

### ISSUE THREAD

**Issue by poyea** [vote4hk/warsinhk#193]
On branch `feat/relation-diagram`, the translation for `status_pending_admission` is missing at the moment.
![image](https://user-images.githubusercontent.com/24757020/78099489-54290900-73e2-11ea-8a35-65ec07348792.png)

**Comment by cswbrian** [comment]
It's becoz it is branched out a while ago and not being rebased yet, it will be resolved when it merges to dev branch.
