### ISSUE TITLE
cannot run with older node version (<=10)

### ISSUE THREAD

**Issue by nandiheath** [vote4hk/warsinhk#195]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Failed to build on node10

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Probably this is because we are using `string.matchAll` which is a node12 function. We better find an alternative for this.

**Comment by wingkwong** [comment]
@nandiheath Gatsby requires Node.js 10.13.0 or higher

**Comment by cswbrian** [comment]
@nandiheath 
https://github.com/nodejs/Release#nodejs-release-working-group

**Comment by yookoala** [comment]
I think you may add a [`.nvmrc`](https://medium.com/@faith__ngetich/locking-down-a-project-to-a-specific-node-version-using-nvmrc-and-or-engines-e5fd19144245) file to hint the node version, then add "using [nvm](https://github.com/nvm-sh/nvm)" into the recommended practice in README somwhere. There is even a [nvm for windows](https://github.com/coreybutler/nvm-windows) project that supports workflow similar to nvm (which supports Linux and Mac). So you may have all platforms covered. It's always nightmare-ish to use OS-bounded node version anyway.

**Comment by nandiheath** [comment]
yeah but what I mean is we shouldn't scarify the node 10 compatibility just because of a simple `string.matchAll` function, which we can easily replace with other implementation.

And I am not opposed to add `.nvmrc` and specify the version in `README` 😀

**Comment by wingkwong** [comment]
I'm revising ``README.md``. I'll include the version in it.

**Comment by wingkwong** [comment]
Closing this issue as it's been handled in https://github.com/nandiheath/warsinhk/commit/0b275bfad36c083f24f9417549798dc0003ea824, https://github.com/nandiheath/warsinhk/commit/08be4e82027bfa370079eb5f750c09063ab3d0a5 and https://github.com/nandiheath/warsinhk/commit/174f007702e65da3c846228f84fa4c2c9ed02888
