### ISSUE TITLE
[World] Add case per 1 million people

### ISSUE THREAD

**Issue by cswbrian** [vote4hk/warsinhk#197]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [ x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Add case per 1M people in https://wars.vote4.hk/world, just like https://www.google.com/covid19-map/

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 2.0.0-beta.X
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by kalvin807** [comment]
Anyone is working on this? I can do this one.

**Comment by cswbrian** [comment]
Feel free to go
https://www.worldometers.info/coronavirus/
https://www.google.com/covid19-map/

**Comment by kalvin807** [comment]
okiee assign to me then. I think I can finish it by this week
