### ISSUE TITLE
Request for CHP number of local case group

### ISSUE THREAD

**Issue by IvanWong222** [vote4hk/warsinhk#258]
Hi, we are doing a research on local COVID-19 database. 

We see the case can be classified by group (e.g. Dancing/Singing Cluster)
But we couldn't find the csv for CHP number of those group, could you please kindly help?

Thank you in advance!

**Comment by lifehome** [comment]
Hello there,

Thanks for the hard work! Unfortunately, none of the internal grouping of confirmed cases and analytic metadata, are disclosed by the government nor the CHP/DH/HA. However, the press release from CHP have different data format from time to time, and if we see an "official" name from the press release, we will prioritize to consider using that name.

Therefore, we have cross-referenced from multiple local news outlet, and also the website previously curated by Dr Pak-leung Ho. So for what we have published on the website, is a handcrafted consensus by our volunteer team, to identify the groups of epidemiologically-related confirm case in laymen terms commonly used by local news outlet.

Sorry can't help much more, but please do let me know if you got further questions!

Thanks! Stay safe and healthy!

-- Ivan

**Comment by ivanwong-222** [comment]
Understood, 
Thank you very much for the information.
