### ISSUE TITLE
looking for a updated CSV for 2022

### ISSUE THREAD

**Issue by JakeSLLeung** [vote4hk/warsinhk#267]
hello @lifehome , happy lunar new year,

Our research (with @wmml1234567890 ) on COVID-19 is still running, but we are lacking the CSV file for 2022, could you please offer a help?

Thank you for your kindly attention

_Originally posted by @JakeSLLeung in https://github.com/vote4hk/warsinhk/issues/244#issuecomment-1026772409_

hello,

As mentioned, we hope to get the link of csv file for 2022, would you please offer a help to our research? Thank you very much.

**Comment by cswbrian** [comment]
@JakeSLLeung 
Please take the following links for 2022 files:

Cases:
https://docs.google.com/spreadsheets/d/e/2PACX-1vTEJyeLTOgntmUjeRhyEB1w_eFD6BUKAEgkR47pp3yXY_XB3IlF7DstsAA0pHz33h2pzGIxGbvGhjMe/pub?gid=0

High Risk Locations
https://docs.google.com/spreadsheets/d/e/2PACX-1vTl_YWJy_osrNeOD0ufyQH4CuWTKCX9ng-tUPpIFXsAdk_ry2uciIt752f9a-yd83IGUtsw2rHQNB0s/pub?gid=0

**Comment by JakeSLLeung** [comment]
@cswbrian 
Thank you for your team effort. Wish all of you have a nice and healthy year!
